/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PageDocIdImport } from './routes/page/$docId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PageDocIdRoute = PageDocIdImport.update({
  id: '/page/$docId',
  path: '/page/$docId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/page/$docId': {
      id: '/page/$docId'
      path: '/page/$docId'
      fullPath: '/page/$docId'
      preLoaderRoute: typeof PageDocIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/page/$docId': typeof PageDocIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/page/$docId': typeof PageDocIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/page/$docId': typeof PageDocIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/page/$docId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/page/$docId'
  id: '__root__' | '/' | '/page/$docId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PageDocIdRoute: typeof PageDocIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PageDocIdRoute: PageDocIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/page/$docId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/page/$docId": {
      "filePath": "page/$docId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
